image: Visual Studio 2017

install:
 # - choco install gitversion.portable -pre -y

nuget:
  account_feed: false

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
#configuration:
#  - Debug
#  - Release

before_build:
  - nuget restore Habitat.sln
 # - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build_script:
  - cmd: msbuild Habitat.sln /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:detailed # /p:PackageVersion=%GitVersion_SemVer%

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:

  - path: src\Project\Habitat\tds\Sitecore.Habitat.Website.Master\bin\Package_Release\*

#---------------------------------#
#      deploy configuration    #
#---------------------------------#
deploy:
  description: 'Habitat'
  provider: GitHub
  auth_token:
    secure: vMfLJBfd7tN7ijjHaiJ1DSbqJzKP7M0i0zJ4k2SSFPj/t+vl9Kp+jFPt/wExjXOa # your encrypted token from GitHub
  artifact: /.*\.update/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only